version: '3.8'

services:
  evolution-api:
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "8081:8081"
    environment:
      # Configurações básicas
      - SERVER_TYPE=http
      - SERVER_PORT=8081
      - CORS_ORIGIN=*
      - CORS_METHODS=POST,GET,PUT,DELETE
      - CORS_CREDENTIALS=true
      
      # Configurações de autenticação
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=YOUR_SECURE_API_KEY_2024
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      
      # Configurações do banco de dados
      - DATABASE_ENABLED=true
      - DATABASE_CONNECTION_URI=file:./db/evolution.db
      - DATABASE_CONNECTION_CLIENT_NAME=evolution_db
      
      # Configurações de cache
      - CACHE_REDIS_ENABLED=false
      - CACHE_LOCAL_ENABLED=true
      
      # Configurações de webhook
      - WEBHOOK_GLOBAL_ENABLED=true
      - WEBHOOK_GLOBAL_URL=https://autocredd-production.up.railway.app/webhook/whatsapp
      - WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS=true
      
      # Configurações de logs
      - LOG_LEVEL=info
      - LOG_COLOR=true
      
      # Configurações de instância
      - DEL_INSTANCE=false
      - DEL_TEMP_INSTANCES=false
      
      # Configurações de QR Code
      - QRCODE_LIMIT=30
      
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
      - evolution_db:/evolution/db
    
    networks:
      - evolution_network

volumes:
  evolution_instances:
  evolution_store:
  evolution_db:

networks:
  evolution_network:
    driver: bridge 