[build]
builder = "nixpacks"
buildCommand = "echo 'Using nixpacks for build'"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[environments.production]
variables = { PORT = "8000", ENVIRONMENT = "production" } 