[build]
builder = "nixpacks"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "always"

[variables]
ENVIRONMENT = "railway"
NODE_VERSION = "18"
PORT = "8000" 